# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies

      - run:
          name: install dependencies
          command: | 
            ls $HOME
            if [ ! -d "/home/circleci/conda" ]; then
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
                /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
                export PATH=$HOME/conda/bin:$PATH
                $HOME/conda/bin/conda install pandas sqlalchemy psycopg2
                $HOME/conda/bin/pip pyathena
            else
                echo "Miniconda is already installed, continuing to build."
            fi
      - save_cache:
          paths:
            - /home/circleci/conda
          key: v2-dependencies
        
      - run:
          name: build container
          command: |
            cd ~/repo
            $HOME/conda/bin/python etl.py
